proto files updated and proto gen script added
comdex-official/comdex pull request #13
Opened 2021-07-28 05:34 UTC by prashantkrv2020

2021-07-28 10:46 UTC, bsrinivas8687 requested changes

2021-07-28 10:46 UTC, bsrinivas8687 commented on .script/protocgen.sh
> +#!/usr/bin/env bash
There is an easy way for generating the code from proto files. Can you please take reference from [here](https://github.com/sentinel-official/hub/blob/development/scripts/proto-gen.sh)

2021-07-28 10:46 UTC, bsrinivas8687 commented on Makefile
> +proto-gen:
Same here too. No need to use Docker. Can be simplified like [this](https://github.com/sentinel-official/hub/blob/development/Makefile#L45)

2021-07-28 10:46 UTC, bsrinivas8687 commented on proto/comdex/cdp/cdp.proto
> +package comdex.cdp;
Please maintain versioning for proto files

2021-07-28 10:46 UTC, bsrinivas8687 commented on proto/comdex/cdp/cdp.proto
> +
Remove multiple empty lines. Use IntelliJ IDEA for this and use clag-format software.

2021-07-28 10:46 UTC, bsrinivas8687 commented on proto/comdex/cdp/cdp.proto
> +  cosmos.base.v1beta1.Coin accumulatedFees = 6 [
Variables of proto messages should be in snakecase

2021-07-28 10:46 UTC, bsrinivas8687 commented on proto/comdex/cdp/query.proto
> +package comdex.cdp;
Give a new line after declaration of proto syntax version

2021-07-28 10:46 UTC, bsrinivas8687 commented on proto/comdex/cdp/cdp.proto
> +  string type = 3 [ (gogoproto.moretags) = "yaml:\"type\"" ];
Why `type` is string here?

2021-07-28 10:46 UTC, bsrinivas8687 commented on proto/comdex/cdp/cdp.proto
> +  cosmos.base.v1beta1.Coin collateral = 4 [
Why cannot we use Coins instead Coin?

2021-07-28 10:46 UTC, bsrinivas8687 commented on proto/comdex/cdp/query.proto
> +service Query {
Move this Query service to end of the file. Also Service should end with "Service". Here it should be QueryService

2021-07-28 10:46 UTC, bsrinivas8687 commented on proto/comdex/cdp/query.proto
> +message GetCDPRequest{
Query requests should start with Prefix "Query"

2021-07-28 10:46 UTC, bsrinivas8687 commented on proto/comdex/cdp/query.proto
> +message GetCDPResponse{
Query responses should start with Prefix "Query"

2021-07-28 10:46 UTC, bsrinivas8687 commented on proto/comdex/cdp/tx.proto
> +syntax = "proto3";
Rename the file name from tx.proto to msg.proto

2021-07-28 10:46 UTC, bsrinivas8687 commented on proto/comdex/cdp/tx.proto
> +message MsgWithdraw{
This should end with `Request`

2021-07-28 10:46 UTC, bsrinivas8687 commented on proto/comdex/cdp/tx.proto
> +  rpc CreateCDP(MsgCreateCDP) returns (MsgCreateCDPResponse);
Here the methods should start with `Msg`

2021-07-28 10:46 UTC, bsrinivas8687 commented on proto/comdex/cdp/query.proto
> +  rpc GetCDP(GetCDPRequest) returns(GetCDPResponse);
Here the methods should start with `Query`

2021-07-28 10:46 UTC, bsrinivas8687 commented on proto/comdex/cdp/cdp.proto
> +message AugmentedCDP{
What is AugmentedCDP? Can we use different name?

2021-07-28 10:48 UTC, bsrinivas8687 commented
PR name is not matching with the file changes. Please update the PR name

2021-07-28 16:40 UTC, prashantkrv2020 commented on proto/comdex/cdp/cdp.proto
> +package comdex.cdp;
done

2021-07-28 16:40 UTC, prashantkrv2020 commented on proto/comdex/cdp/cdp.proto
> +  string type = 3 [ (gogoproto.moretags) = "yaml:\"type\"" ];
its the cdp type that will in string format

2021-07-28 16:40 UTC, prashantkrv2020 commented on proto/comdex/cdp/cdp.proto
> +  cosmos.base.v1beta1.Coin collateral = 4 [
collateral can be only of a single coin as of now

2021-07-28 16:40 UTC, prashantkrv2020 commented on proto/comdex/cdp/cdp.proto
> +  cosmos.base.v1beta1.Coin accumulatedFees = 6 [
updated

2021-07-28 16:40 UTC, prashantkrv2020 commented on proto/comdex/cdp/cdp.proto
> +message AugmentedCDP{
augumented cdp is the cdp with extra information with it. Will take up name changes/corrections later. right now have to get a simple cdp running asap

2021-07-28 16:40 UTC, prashantkrv2020 commented on proto/comdex/cdp/query.proto
> +service Query {
If I update it to QueryService, then it will generate QueryServiceServer struct. this is fine

2021-07-28 16:40 UTC, prashantkrv2020 commented on proto/comdex/cdp/tx.proto
> +syntax = "proto3";
will follow the current cosmos sdk structure. This is fine

2021-07-28 16:40 UTC, prashantkrv2020 commented on proto/comdex/cdp/tx.proto
> +  rpc CreateCDP(MsgCreateCDP) returns (MsgCreateCDPResponse);
Both rpc methods and the request message will have the same name. Not desirable

2021-07-28 16:40 UTC, prashantkrv2020 commented on proto/comdex/cdp/tx.proto
> +message MsgWithdraw{
No need. MsgWithdraw already states that its a message to withdraw. Adding request on top would be an overkill

2021-07-28 17:00 UTC, dheerajkd30 commented on proto/comdex/cdp/tx.proto
> +message MsgWithdraw{
Let's change it to MsgWithdrawRequest. It will be good practice to follow the naming convention. Would suggest and  let's follow the same for Request and Response.

2021-07-28 17:32 UTC, dheerajkd30 commented on proto/comdex/cdp/query.proto
> +message GetCDPRequest{
Cosmos has been following the convention as QueryGetCDPRequest. Let's change it and will follow across.

2021-07-28 17:41 UTC, dheerajkd30 submitted a review, later dismissed
Let's follow the naming convention for some files. Please make changes accordingly. again we can have a discussion on it but if we are referring to some repo let's do it that way.

2021-07-28 18:46 UTC, bsrinivas8687 commented on proto/comdex/cdp/query.proto
> +message GetCDPRequest{
Yeah, it's not because the Cosmos is following but it's the standard. Check [here](https://docs.buf.build)

2021-07-28 18:47 UTC, bsrinivas8687 commented on proto/comdex/cdp/tx.proto
> +message MsgWithdraw{
> No need. MsgWithdraw already states that its a message to withdraw. Adding request on top would be an overkill

No it wont because it's the standard and most of the projects/developers follow

2021-07-29 05:46 UTC, prashantkrv2020 commented
> Let's follow the naming convention for some files. Please make changes accordingly. again we can have a discussion on it but if we are referring to some repo let's do it that way.

anything specific you're talking about?

2021-07-29 05:57 UTC, dheerajkd30 commented
> > Let's follow the naming convention for some files. Please make changes accordingly. again we can have a discussion on it but if we are referring to some repo let's do it that way.
> 
> anything specific you're talking about?

> This was general comment in case we need to discuss and finalize on any conventions. Have provided comments where we need changes specifically.

2021-07-29 09:20 UTC, prashantkrv2020 commented on proto/comdex/cdp/tx.proto
> +message MsgWithdraw{
I'm following the standard that most developers follow. Have been taking references from major cosmos projects such as cosmos sdk, osmosis, wasmd. They all have done the same.

2021-07-29 10:08 UTC, bsrinivas8687 commented on proto/comdex/cdp/tx.proto
> +message MsgWithdraw{
True. What those projects following is not the standard naming convenstion set by the gRPC community.

`All request and response messages are named after the RPC, either by naming them MethodNameRequest, MethodNameResponse or ServiceNameMethodNameRequest, ServiceNameMethodNameResponse`

2021-07-29 10:20 UTC, dheerajkd30 commented on proto/comdex/cdp/tx.proto
> +message MsgWithdraw{
Agreed. We should follow the above convention in our project. Let's change it and agree to follow across.

2021-07-29 13:11 UTC, dheerajkd30 reviewed
reviewed.

2021-07-29 13:11 UTC, dheerajkd30 commented on proto/comdex/cdp/v1alpha1/msg.proto
> +service Msg {
Might have missed on call, but I thought we agreed to change it to MsgService. And for rpc's to prefix with Msg like MsgCreateCDP and same for Query.proto?

2021-07-29 13:23 UTC, bsrinivas8687 approved these changes

2021-07-29 13:23 UTC, bsrinivas8687 commented on proto/comdex/cdp/v1alpha1/cdp.proto
> +    (gogoproto.moretags) = "yaml:\"accumulatedFees\"",
Please use snake_case for YAML tags

2021-07-29 13:23 UTC, bsrinivas8687 commented on proto/comdex/cdp/v1alpha1/msg.proto
> +service Msg {
Yes, also here Msg gRPC service methods should start with Msg

2021-07-29 13:25 UTC, merged