CDP client changes
comdex-official/comdex pull request #15
Opened 2021-07-31 17:59 UTC by dheerajkd30

2021-08-01 22:42 UTC, prashantkrv2020 commented on x/cdp/client/cli/query.go
> +	cmd.AddCommand(QueryCdp(),
add a new line after AddCommand(

2021-08-01 22:42 UTC, prashantkrv2020 commented on x/cdp/client/cli/query.go
> +		QueryCdpDeposits(),
you can remove this particular query . Since we don't have different users depositing for same cdp.

2021-08-01 22:42 UTC, prashantkrv2020 commented on x/cdp/client/cli/query.go
> +			if error != nil {
don't use both err and error for errors. We will follow just err everywhere.

2021-08-01 22:42 UTC, prashantkrv2020 commented on x/cdp/client/cli/query.go
> +				_, error = sdk.AccAddressFromBech32(args[0])
No need to write this expression like this. Just for := for initialization

2021-08-01 22:42 UTC, prashantkrv2020 commented on x/cdp/client/cli/query.go
> +			qc := types.NewQueryServiceClient(ctx)
it is better to use short names only for popular objects. Better to  write queryClient here.

2021-08-01 22:42 UTC, prashantkrv2020 commented on x/cdp/client/cli/query.go
> +				_, error = sdk.AccAddressFromBech32(args[0])
same as above

2021-08-01 22:42 UTC, prashantkrv2020 commented on x/cdp/client/rest/tx.go
> +func postCdp(ctx client.Context) http.HandlerFunc {
dont need to prefix it with post here. can keep it simple as createCdp

2021-08-03 08:10 UTC, prashantkrv2020 submitted a review, later dismissed

2021-08-03 08:39 UTC, bsrinivas8687 requested changes

2021-08-03 08:39 UTC, bsrinivas8687 commented on x/cdp/client/cli/query.go
> +		Use:   "cdp [owner-addr] [collateral-type]",
Is the collateral type is necessary?

2021-08-03 08:39 UTC, bsrinivas8687 commented on x/cdp/client/cli/query.go
> +				_, error = sdk.AccAddressFromBech32(args[0])
Yes, please use err instead error because error is a keyword

2021-08-03 08:39 UTC, bsrinivas8687 commented on x/cdp/client/cli/query.go
> +			res, err := queryClient.QueryCDP(context.Background(), &types.QueryCDPRequest{
Why the request is empty?

2021-08-03 08:39 UTC, bsrinivas8687 commented on x/cdp/client/cli/tx.go
> +			ctx, err := client.GetClientQueryContext(cmd)
This should be GetClientTxContext

2021-08-03 08:39 UTC, bsrinivas8687 commented on x/cdp/client/rest/tx.go
> +package rest
Can delete TX for REST

2021-08-03 08:39 UTC, bsrinivas8687 commented on x/cdp/types/errors.go
>  // x/cdp module sentinel errors
Remove this comment Hahaha

2021-08-03 08:44 UTC, prashantkrv2020 commented on x/cdp/client/rest/tx.go
> +package rest
was thinking of keeping support for rest tx as well for now. will remove them in time.

2021-08-03 09:03 UTC, dheerajkd30 commented on x/cdp/client/cli/query.go
> +			res, err := queryClient.QueryCDP(context.Background(), &types.QueryCDPRequest{
will update it, once the request struct is finalized. will update the logic in func once basic req/resp works out. that's what we decided.

2021-08-03 09:06 UTC, dheerajkd30 commented on x/cdp/client/cli/query.go
> +		Use:   "cdp [owner-addr] [collateral-type]",
removed.

2021-08-03 09:09 UTC, dheerajkd30 commented on x/cdp/client/cli/query.go
> +				_, error = sdk.AccAddressFromBech32(args[0])
removed the exp

2021-08-03 09:27 UTC, bsrinivas8687 commented on x/cdp/client/rest/tx.go
> +package rest
Can you please explain why? It's not secure and recommended.

2021-08-03 09:28 UTC, bsrinivas8687 approved these changes

2021-08-03 09:28 UTC, merged