Scripts added and code refactor
comdex-official/comdex pull request #17
Opened 2021-08-03 09:50 UTC by prashantkrv2020

2021-08-03 09:56 UTC, dheerajkd30 submitted a review, later dismissed

2021-08-04 08:23 UTC, bsrinivas8687 requested changes

2021-08-04 08:23 UTC, bsrinivas8687 commented on .script/setup.sh
> +make all
We don't need three different scripts for this. Even I would say we don't need these scripts

2021-08-04 20:12 UTC, prashantkrv2020 commented on .script/setup.sh
> +make all
Right now it looks like a single-line script but we can add a lot of customizations to it. And anyone using it would just have to run the script

2021-08-05 13:50 UTC, dheerajkd30 submitted a review, later dismissed

2021-08-11 13:57 UTC, dheerajkd30 approved these changes

2021-08-11 20:59 UTC, bsrinivas8687 approved these changes

2021-08-11 20:59 UTC, merged