Keeper updates
comdex-official/comdex pull request #18
Opened 2021-08-03 12:59 UTC by prashantkrv2020

2021-08-03 15:37 UTC, dheerajkd30 commented on x/cdp/client/cli/query.go
>  		Args:  cobra.ExactArgs(1),
ExactArgs(2) ?

2021-08-03 16:47 UTC, dheerajkd30 requested changes

2021-08-03 16:47 UTC, dheerajkd30 commented on x/cdp/keeper/params.go
> +func (k Keeper) getLiquidationRatio(ctx sdk.Context, collateralType string) sdk.Dec {
func name correction >> Get..

2021-08-03 16:47 UTC, dheerajkd30 commented on x/cdp/types/errors.go
> +	ErrSample                 = sdkerrors.Register(ModuleName, 106, "sample error")
let's follow one convention Err or Error prefix. update either one.

2021-08-05 07:16 UTC, dheerajkd30 requested changes

2021-08-05 07:16 UTC, dheerajkd30 commented on x/cdp/keeper/cdp.go
> +func (k Keeper) GetCdpIdsByOnwer(ctx sdk.Context, owner sdk.AccAddress) (types.CdpIdList, bool) {
Owner** spelling mistake

2021-08-05 07:24 UTC, dheerajkd30 commented on x/cdp/keeper/cdp.go
> +func (k Keeper) GetCdpIdsByOnwer(ctx sdk.Context, owner sdk.AccAddress) (types.CdpIdList, bool) {
udated.

2021-08-05 07:25 UTC, dheerajkd30 approved these changes

2021-08-05 08:39 UTC, bsrinivas8687 approved these changes

2021-08-05 08:40 UTC, merged