fixed admin issue
comdex-official/comdex pull request #59
Opened 2021-09-28 11:41 UTC by prashantkrv2020

2021-09-28 11:50 UTC, bsrinivas8687 requested changes

2021-09-28 11:50 UTC, bsrinivas8687 commented on app/app.go
> +	app.paramsKeeper.Subspace(assettypes.ModuleName).WithKeyTable(assettypes.ParamKeyTable())
This should not be like this. Remove WithKeyTable initialization here. It should be in NewKeeper function

2021-09-28 11:50 UTC, bsrinivas8687 commented on x/asset/types/params.go
> +	DefaultAdmin = "comdex1pkkayn066msg6kn33wnl5srhdt3tnu2v9jjqu0"
Do not define default admin. Instead we can mention it in instructions to add the admin address in genesis.json file

2021-09-28 13:01 UTC, prashantkrv2020 commented on x/asset/types/params.go
> +	DefaultAdmin = "comdex1pkkayn066msg6kn33wnl5srhdt3tnu2v9jjqu0"
default values are defined everywhere, all cosmos and cosmos-based modules. Tried adding the admin address in genesis, it still expects and picks up the default value

2021-09-29 13:45 UTC, bsrinivas8687 approved these changes

2021-09-29 13:45 UTC, merged