pool voting bindings added
comdex-official/comdex pull request #647
Opened 2022-12-21 10:58 UTC by cgsingh33

2022-12-23 09:51 UTC, dheerajkd30 approved these changes

2022-12-26 07:46 UTC, Subham2804 approved these changes

2022-12-26 09:03 UTC, pratikasr requested changes
scripts/.DS_Store pls remove this

2022-12-26 09:10 UTC, pratikasr requested changes
comdex/x/auction/keeper/dutch_test.go:506 pls fix the failing testcase

2022-12-26 09:14 UTC, cgsingh33 commented
> comdex/x/auction/keeper/dutch_test.go:506 pls fix the failing testcase

fixed in https://github.com/comdex-official/comdex/pull/639

2022-12-26 09:22 UTC, pratikasr approved these changes

2022-12-30 04:05 UTC, merged