Reward dist price inactive issue fix
comdex-official/comdex pull request #657
Opened 2023-01-19 13:37 UTC by vishnukumavat

2023-01-20 03:46 UTC, pratikasr approved these changes

2023-01-20 07:55 UTC, dheerajkd30 approved these changes

2023-01-20 19:33 UTC, cgsingh33 requested changes

2023-01-20 19:33 UTC, cgsingh33 commented on x/liquidity/keeper/rewards.go
> +		priceInactiveBlockCount := ctx.BlockHeight() - price.DiscardedHeightDiff
first, call GetDiscardData
priceInactiveBlockCount := ctx.BlockHeight() - price.DiscardedHeightDiff
this should be 
priceInactiveBlockCount := ctx.BlockHeight() - block_height(from GetDiscardData)

2023-01-20 19:33 UTC, cgsingh33 commented on x/liquidity/keeper/rewards.go
> +		priceInactiveBlockCount := ctx.BlockHeight() - price.DiscardedHeightDiff
@vishnukumavat

2023-01-20 19:37 UTC, cgsingh33 approved these changes

2023-01-22 06:47 UTC, dheerajkd30 approved these changes

2023-01-22 06:47 UTC, merged